rovercode/rovercode-web

.gitignore, pytest.ini, requirements/local.txt, rovercode_web/users/tests/test_adapters.py
* Add `pytest-cov` to determine test coverage
* Add testing for adapters to bring test coverage to 100%
Current output:
```
$ sudo docker-compose -f dev.yml run django py.test
Postgres is up - continuing...
Test session starts (platform: linux, Python 3.5.2, pytest 3.0.6, pytest-sugar 0.8.0)
Django settings: config.settings.local (from ini file)
rootdir: /app, inifile: pytest.ini
plugins: sugar-0.8.0, django-3.1.2, cov-2.4.0
mission_control/static/closure-library/closure/bin/labs/code/generate_jsdoc_test.py ✓✓✓✓✓✓                                                                                                       26% ██▋       
rovercode_web/users/tests/test_adapters.py ✓✓ …
```
=> Add test coverage

compose/django/Dockerfile-dev, dev.yml
I'm able to run `sudo docker-compose -f dev.yml up` and everything is up and running.
=> Fix bringing up celery

README.rst
Giving up on Gitter because it doesn't send us notifications.
=> Changes readme to point to slack for chat

config/settings/common.py, rovercode_web/taskapp/__init__.py, rovercode_web/taskapp/celery.py
Importing the Rover model works. However, there's still some issue that I'm getting trying to bring up the celery containers:
```
ImportError: No module named 'rovercode_web.taskapp.celery.CeleryConfig'; 'rovercode_web.taskapp.celery' is not a package
```
=> Fix importing of Rover model

README.rst
Uses slackin hosted on a little Heroku app.
=> Points chat link to public gateway to our slack

.gitmodules, appspec.yml, deploy-scripts/clone_subrepos.sh
This adds a script to manually pull the subrepos that CodeDeploy failed to pull.
=> Code deploy must manually pull subrepos

README.rst, config/settings/local.py, docs/detailed-usage.rst, docs/index.rst, mission_control/static/js/rover-api.js, rovercode_web/templates/base.html
mission-control isn't perfect (especially when not logged in), but it's still a decent way to see what it is we're making. Added link to the homepage.
=> Add demo link

mission_control/forms.py, mission_control/templates/rover_list.html, mission_control/templates/rover_settings.html, mission_control/tests/test_urls.py, mission_control/tests/test_views.py, mission_control/urls.py, mission_control/views.py
More of #19. This allows for changing the rover pin settings. There are a couple disabled fields for features that will be added later.
=> Create settings page to change rover settings

mission_control/static/js/mission-control.js, mission_control/templates/home.html
Addresses #23 using [Ace](https://ace.c9.io/)
* Added "Show Me The Code!" button in the nav bar.
* Added modal to display the code. (Set to `read-only` for now)
Example (one of many themes):
=> Add a viewer for generated javascript code

mission_control/static/js/cred-download.js, mission_control/templates/rover_settings.html
Sorry, I merged the previous PR into a different branch instead of into development. Would you mind reapproving this?
=> Recreating 107 download creds PR

compose/django/gunicorn.sh
Makes sure that migrations are run each time that the application is launched in production.
=> Run migrations on launch

docs/detailed-usage.rst, mission_control/static/js/bd-api.js, mission_control/static/js/mission-control.js, mission_control/templates/home.html
Closes #21 
Also, found that all the links to the API were broken in the `mission_control` javascript when they were moved into `/api/v1`. Currently, there are errors saving/loading block diagrams and rover lists in `mission_control`. There was also a jQuery selector error for the play button color change.
=> Pause stops motors

README.rst
=> Fix readme link

appspec.yml, deploy-scripts/remove_prev_install.sh
Our deploy scripts hadn't been tested against a fresh machine, so this fixes up a few small things that caused errors.
=> Fix up small things for fresh deploy

compose/django/Dockerfile, compose/django/Dockerfile-dev, compose/django/entrypoint.sh, config/settings/common.py, env.example
As I always do, I forgot to change the target branch of this PR before merging. Do you mind approving it again?
=> Add support for remote postgres

.travis.yml
Twice in one night. Merged into wrong branch. Mind approving again?
=> Add beta deploy on new server

.travis.yml
Adds deployment to the production EC2 on our new AWS account.
=> Add master deploy on new account

rovercode_web/blog/tests/test_views.py, rovercode_web/blog/views.py
The `PostViewSet` allowed creating a blog post by anyone.
=> Restrict creating blog posts to admins

mission_control/static/js/bd-api.js, mission_control/static/js/mission-control.js, mission_control/templates/home.html
Closes #117 
Removes the broken feature since there is only one place to have the block diagram.
=> Remove block diagram upload/download features

api/urls.py
Required for logging in with username and password to get a JWT.
=> Add route for basic authentication with jwt

middleware/channels_jwt_middleware.py, middleware/tests/test_channels_jwt_middleware.py
Previously, we had a 500 error when a JWT was present but expired. This handles the exception and makes the middleware return, allowing other middleware to attempt to authenticate the user.
=> Handle JWT verification error in channels middleware

realtime/templates/realtime/room.html
This adds a debug buttons that generate motor commands to the realtime debug page. It also makes the testbox send arbitrary text so that custom JSON messages can be used.
This is a PR into the alpha branch. For now, I think we should PR into alpha as the first-level working branch. After the deployment changes are worked out, I think we could get rid of the alpha branch and let the development branch deploy to both beta.rovercode.com and alpha.rovercode.com, which would then differ only in infrastructure. What do you think?
=> Add debug buttons to realtime room

api/urls.py, api/views.py, mission_control/serializers.py
The list of tags can be used as selection choices when adding tags to a program
=> Add API to access tags

config/settings/common.py
=> Increase token expiration

.travis.yml, compose/nginx/nginx-secure.conf, compose/nginx/nginx.conf, deploy-scripts/rename_app.sh, deploy-scripts/start_app.sh, docker-compose.yml, ecr-deploy.sh
* Removes `certbot`
* Sets Travis CI to build and push images to ECR
* Changes CodeDeploy to login to ECR and use built images
=> ECR deploy

api/tests/test_views.py, curriculum/serializers.py
Only id and owner status needed for active block diagram. The link was not really useful
=> Course API changes

README.rst, api/tests/test_views.py, api/urls.py, api/views.py
* Only list non-reference programs in the community view
=> Push to Beta

api/tests/test_views.py, api/views.py, config/settings/common.py, mission_control/templates/email/issue_report.html
Allow the user to report an issue with a program. The user can enter a description and the staff will be notified.
=> Add endpoint to report issue with program

api/views.py
This would allow the user to see programs only made by a particular user
=> Allow for searching by creator

api/tests/test_views.py, rovercode_web/users/apps.py, rovercode_web/users/signals/handlers.py, rovercode_web/users/tests/test_handlers.py, rovercode_web/users/tests/test_models.py, rovercode_web/users/tests/test_utils.py
When a new user registers, create the external user in the subscription service
=> Create external user on account creation

config/settings/production.py, deploy-scripts/remove_prev_install.sh
Also, should only remove images related to this project instead of all images on the host
=> Fix sentry

api/tests/test_views.py, mission_control/serializers.py
When blank blog answers are saved, remove any stored answer for that question
=> Handle blank blog answers

compose/profanity/Dockerfile
The current cgit.freedesktop.org is not available and might have been removed. Fetch instead from GitHub which will hopefully be more available
=> Fetch dictionary from different location

api/tests/test_views.py, mission_control/serializers.py
Checks that the questions being answered are for the block diagram being modified
=> Disallow answering a question to a different program
