rovercode/rovercode-web

README.rst
Coverall is being weird about the build status of the development branch. This will just specify no branch, and hopefully it chooses the default.
=> Changes coverall svg url

compose/nginx/Dockerfile, compose/postgres/Dockerfile, dev.yml, docker-compose.yml
Use the `alpine` version of official images since they are much smaller
and debugging won't be needed or other packages installed within them.
After merging, manually remove all of the older large images if desired.
=> Reduce the size of images

.coveragerc, mission_control/static/js/mission-control.js, mission_control/static/js/rover-api.js, mission_control/templates/home.html, mission_control/templates/list.html, mission_control/tests/test_urls.py, mission_control/tests/test_views.py, mission_control/urls.py, mission_control/views.py, requirements/local.txt, rovercode_web/templates/base.html
Addresses issue #3 
Creates a page that lists all of the logged in user's block diagrams. Hopefully someone with more artistic talent can make it look better, but all of the data is there. The block diagram buttons currently don't go anywhere. I'm not sure how that's going to tie into the blockly interface.
When a user is logged in, the `My Block Diagrams` navbar button is visible:
When clicked, takes the user to a page listing only the block diagrams created by that user:
=> Add page for logged in user to see user's block diagrams

.coveragerc, config/settings/common.py, mission_control/tests/test_views.py, pytest.ini
Configures coverage so that now the `.coveragerc` determines which directories are being checked. Both the `rovercode_web` and `mission_control` directories are now included. A couple of tests were missing for `mission_control` that are now added to bring the coverage back to 100%.
=> Configures coverage to check multiple directories

mission_control/views.py
The `django-filters` `DjangoFilterBackend` provides a nice `Filters` button
on the browsable API.
=> Select the correct Django filter backend

requirements/base.txt, requirements/local.txt
I think the django-filters requirement needs to be in base so that the production build has it, too.
=> Moves django-filters from local to base

.prospector.yaml, .travis.yml, mission_control/__init__.py, mission_control/admin.py, mission_control/apps.py, mission_control/models.py, mission_control/serializers.py, mission_control/tests.py, mission_control/tests/test_models.py, mission_control/tests/test_urls.py, mission_control/tests/test_utils.py, mission_control/tests/test_views.py, mission_control/urls.py, mission_control/utils.py, mission_control/views.py, requirements/base.txt, rovercode_web/__init__.py, setup.cfg
This uses [prospector](https://github.com/landscapeio/prospector) to check all of the python files against `dodgy`, `mccabe`, `pep257`, `pep8`, `pyflakes`, and `pylint`. All of the files have been updated to pass. Travis CI has been configured to run the check as part of testing.
To run manually:
```
sudo docker-compose -f dev.yml run django prospector
```
=> Add Python linting check

mission_control/static/js/mission-control.js, mission_control/templates/home.html, requirements/base.txt
When running in production, the csrf token was not available in the cookie. So, this includes it directly in the DOM as shown [here](https://docs.djangoproject.com/en/1.11/ref/csrf/#acquiring-the-token-if-csrf-use-sessions-is-true).
=> Includes csrf token more directly.

compose/nginx/Dockerfile
Not sure what changed about the official nginx Docker image, but suddenly `ps` was unavailable.
=> Adds install of procps to nginx Dockerfile

mission_control/serializers.py, mission_control/tests/test_views.py, mission_control/views.py
* Requires the user to be logged in to access the block diagram API.
* User can only access the user's block diagrams.
* Any superuser accounts can access all block diagrams through the API.
* Sets user to the logged in user that created the block diagram.
=> Add permissions check to block diagram API

.travis.yml
AWS CodeDeploy did not like seeing aninternetof/rovercode-web after we switched to rovercode/rovercode-web
=> Update repo owner in travis.yml

compose/nginx/nginx.conf
Closes #96
Currently, Django is responding to blank host header requests. It is better to not even allow it through according to [nginx](https://nginx.org/en/docs/http/request_processing.html#how_to_prevent_undefined_server_names).
This will stop messages to Sentry.
It is currently running on Beta as a test. Accessing Beta normally seems to be functioning properly.
Before:
```
$ http --verify no https://52.201.242.57
/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py:794: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
InsecureRequestWarning)
HTTP/1.1 400 Bad Request
Connection: keep-alive
Content-Type: text/html
Date: Sat, 12 Aug 2017 04:34:50 GMT …
```
=> Block missing host header requests

compose/nginx/nginx-secure.conf
=> Block missing host header on 80 and 443 in the correct config file

compose/nginx/nginx-secure.conf
Closes #96 
The secure port block requires SSL configuration. Connecting to `beta.rovercode.com` still functions correctly.
Client:
```
$ http --verify no https://52.201.242.57
/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py:794: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
InsecureRequestWarning)
http: error: ConnectionError: ('Connection aborted.', BadStatusLine("''",))
$ http http://52.201.242.57             
http: error: ConnectionError: ('Connection aborted.', BadStatusLine("''",))
```
Server:
```
nginx_1     | 73.168.181.206 - - [13/Aug/2017:00:19:26 +0000] "beta.rovercode.com" "GET / HTTP/1.1" 200 3329 "-" "Mozilla/5.0 (X11; Linux x86_64) …
```
=> Fix broken nginx blocking of missing host header

docker-compose.yml
The certificate was failing to update on the live servers, and this change seems to have fixed it. LetsEncrypt switched to a new image location/name on DockerHub, and apparently stopped updating the old one.
=> Point to newer certbot image

api/apps.py, api/tests/test_apps.py, config/settings/common.py, config/urls.py, requirements/base.txt
Handles the backend parts of #82.
Next, we need to figure out how we want to integrate this into the UI. Currently, just uses the default templates from [Django OAuth Toolkit](https://github.com/evonove/django-oauth-toolkit).
**New URLs**
```
/oauth2/applications/	oauth2_provider.views.application.ApplicationList	oauth2_provider:list	
/oauth2/applications/<pk>/	oauth2_provider.views.application.ApplicationDetail	oauth2_provider:detail	
/oauth2/applications/<pk>/delete/	oauth2_provider.views.application.ApplicationDelete	oauth2_provider:delete	
/oauth2/applications/<pk>/update/	oauth2_provider.views.application.ApplicationUpdate	oauth2_provider:update	
/oauth2/applications/register/	oauth2_provider.views.application.ApplicationRegistration	oauth2_provider:register	
/oauth2/authorize/ …
```
=> Backend OAuth Integration

mission_control/forms.py, mission_control/templates/rover_list.html, mission_control/templates/rover_settings.html, mission_control/tests/test_urls.py, mission_control/tests/test_views.py, mission_control/urls.py, mission_control/views.py
Partially addresses #105.
Adds page to create new rover, with a button to get there.
Also, make the rover settings form use bootstrap form-control.
Still to do: add a relationship between the rover model and the rover OAuth model, and make the new-rover view also create the OAuth model.
=> Add form to create new rover

mission_control/static/js/cred-download.js, mission_control/templates/rover_settings.html
Instead of displaying them on the page, this makes a button to download the rover's oauth2 credentials as a .env file.
=> Make rover oauth2 credentials downloadable

mission_control/static/js/bd-api.js, requirements/base.txt
Ran into this when trying to download a block diagram. It always fails because of #117 but this fixes the error handling associated with a failure.
=> Use correct error method name for $.get()

api/tests/test_views.py, config/settings/common.py, mission_control/serializers.py
This allows the rover to query the API for itself by client_id instead of by name, eliminating the need
for the name to be in the .env
=> Add client_id to rover model serialization

compose/django/Dockerfile, compose/django/Dockerfile-dev, compose/django/entrypoint.sh, config/settings/common.py, env.example
Add env vars to allow other postgres hosts. If nothing in the .envs on our servers changes, this change should have no effect. But, if in the .env we specify AWS RDS Postgres as the host, that  will be used.
My migration strategy is:
1. docker-compose down
2. Migrate the content from the in-container postgres to the remote AWS RDS in our new AWS account. I tried this out using pg_dump and psql commands, and it seemed to go well.
3. Set the .env to point to the remote AWS RDS.
4. docker-composer up
I would do those steps first on the development server to see how it goes, then do the same in prod after we release.
I also added the ability to enable SSL for our connection to the remote AWS RDS. If needed in the future, we could add more flexibility for what certificate to use, but I didn't …
=> Add env vars to allow other postgres targets

.travis.yml
This adds a new deployment to Travis: beta-rovercode-web on our new AWS account.
The diff really botched it. Nothing changed except the addition of the new deploy block.
=> Add beta deploy on new server

.travis.yml
The applications and deployment groups should have the same names. I had a copy-paste error on the new beta deployment.
=> Correct deployment group

.travis.yml
To get the new beta deploy to work, I did three things:
* Regenerate the encrypted aws secret. The only reliable way I've been able to do it is to use `travis setup codedeploy` wizard, copy the deploy block it makes (it will have wiped out your other deploy blocks), git checkout to get your original deploy blocks back, then paste in your new one.
* Get rid of the `matrix:`. I'm not 100% that it needed to be taken out, but I believe my experiments that included it did not work.
* Add region. It defaults to us-east-1, which worked for our old account, but the new one needs us-east-2.
=> Correct the new beta deploy

api/tests/test_views.py, api/views.py, mission_control/filters.py, mission_control/static/js/cred-download.js
Fixes #130.
The rover needs to be able to find itself by oauth client id, so this adds a filter for that to the rover REST API.
Also, the formatting of the credentials file download was wacky, so I fixed that.
=> Oauth client_id filter for rover API

mission_control/static/js/blockly-api.js
Not sure how it was working before, but these `.data`s are not necessary!
=> Fix bug with blockly api arguments

api/urls.py, api/views.py, config/settings/common.py, requirements/base.txt, rovercode_web/blog/views.py
Changes from the Django REST Framework browsable UI to [Swagger UI](https://swagger.io/swagger-ui/). Swagger is accessible at `/api/`. Endpoints or operations that the user is not permitted to use are hidden.
=> API documentation with Swagger UI

requirements/base.txt
This update allows for being on a more stable version as well as using a
released version of `django-oauth-toolkit` which now has signal support.
=> Update Django to latest LTS version

config/settings/common.py, rovercode_web/templates/account/login.html, rovercode_web/templates/base.html
Add buttons to use `GitHub` and `Google` for authentication. This won't "just work" as we'll need to register applications in the `rovercode` `Google` and `GitHub` organizations. Then, use the Django admin to enter the credentials in the deployed application. `Twitter` and `Facebook` can be added fairly easily as well.
=> Add social auth for account sign in

compose/nginx/start.sh
The `ps` command returns information in different columns so the `start.sh` script for `nginx` was incorrectly trying to kill the wrong thing and exiting. This fixes the issue and it currently is running on `beta` with this applied manually.
=> Fix nginx startup script for alpine system

.travis.yml
Prospector was failing to run because there were multiple script sections in the travis.yaml.
=> Remove multiple travis scripts

.travis.yml
We had 4 codedeploy blocks: two for our current account and two for the old account. I accidentally switched all of the over to the new access key. This made the old two identical to the new two, except in us-east-1 instead of us-east-2. Travis failed because it could find any codedeploy applications in us-east-1.
Instead of reverting the old two, I'm removing them.
=> Remove old account deploys

Pipfile, Pipfile.lock
Newer versions of DRF cause swagger UI to use `http` requests when using
`try it out` which breaks on a production deploy using `https`. There is a
selection for `schemes` but it only has `http` as a choice. It's not clear
what is causing this issue and it is easier for now to just go back to the
working version.
Also, newer versions of DRF have built-in interactive API documentation support that we might want to switch to: http://www.django-rest-framework.org/topics/3.6-announcement/
It's currently in this broken condition on https://beta.rovercode.com/api/
=> Downgrade DRF to fix swagger UI issue

config/settings/common.py, rovercode_web/users/forms.py, rovercode_web/users/tests/test_forms.py
Closes #190 
Any email address entered now shows:
Even if the email is not associated with any user in the system. The email is still sent if the user is in the system.
This is the original form: https://github.com/pennersr/django-allauth/blob/master/allauth/account/forms.py#L499
=> Hide knowledge of invalid email addresses in password reset

config/urls.py, rovercode_web/templates/registration/password_reset_email.html
The password reset view needs `password_reset_confirm` to be defined to generate the proper `uid` and `token`. For the new frontend, the link in the email needs to be changed to point to the frontend route. For the email link to work in development, the `domain` for the `Site` needs to be changed to `localhost:8080` to hit the frontend.
From a Django shell:
```
site = Site.objects.first()
site.domain = 'localhost:8080'
site.save()
```
The email can be seen in `mailhog` on `http://localhost:8025`.
For the production case, this won't be an issue since the backend and frontend will be on the same domain.
=> Password reset

config/settings/common.py
The login callback route hadn't been moved to `/accounts` like the other routes
=> Move login callback to be consistent with other account routes

compose/django/Dockerfile
I was missing a line-continuation `\` in the dockerfile. 
I fixed that manually on the beta EC2, and both the https and wss routes work!
=> Add missing line continuation

config/asgi.py, middleware/channels_jwt_middleware.py, middleware/channels_oauth2_middleware.py, middleware/tests/test_channels_jwt_middleware.py, middleware/tests/test_channels_oauth2_middleware.py
This creates Channels middleware to validate via OAuth2 and adds it to the Realtime app.
The middleare validates tokens that appear as Bearer tokens in the Authorization header. This works great for us, because unlike browser websocket clients, the rover's Python websocket client is capable of adding custom headers to the websocket initiation request.
=> Add OAuth2 support to realtime

middleware/channels_jwt_middleware.py, middleware/channels_oauth2_middleware.py, middleware/tests/test_channels_jwt_middleware.py, middleware/tests/test_channels_oauth2_middleware.py, mission_control/templates/rover_settings.html, realtime/consumers.py
This PR makes the standard Django session auth work with Channels (in addition to the jwt auth used by the React app and the Oauth2 auth used by the rover). Enabling standard Django session auth allows us to view the websocket debug chatroom without having to use the React app to get a jwt first.
Support for session auth was already in place, but it was broken because the other middleware was returning `AnonymousUser` instead of `None` when they were not being used.
Also, I added a link on the old rover detail view to the debug websocket chatroom for that rover, just for my ease while debugging.
=> Channels auth improvements

realtime/consumers.py, realtime/templates/realtime/room.html
Before, the realtime websocket consume tried to extract a `message` field from the incoming JSON payload and echoed it to all clients in the group.
This PR makes it echo the entire JSON payload instead. This will allow us to define a JSON protocol between clients.
The result looks like this:
=> Make realtime pass whole JSON messages

docker-compose.yml
This exposes ports 5000 and 6000 from inside the Docker containers. This is necessary, because we now use CloudFront as the router instead of Nginx.
=> Expose django ports in docker-compose

api/tests/test_views.py, mission_control/serializers.py
I think this needs to be fixed as well. The API should return the `400` when a duplicate name is used. It previously had an `IntegrityError` which probably would've been a `500` response
=> Correctly handle user adding rover with same name

api/tests/test_views.py, mission_control/serializers.py
This fixes a bug that caused Rover oauth applications to be created with `None` user.
It also adds to the test a section that would have caught this bug.
=> Fix rover app creation user bug

api/tests/test_views.py, config/settings/common.py, mission_control/pagination.py
Adds `total_pages` to the output and allows setting `size` to change the page size:
=> Customize pagination

api/tests/test_views.py, mission_control/serializers.py
Closes #221 
**This is a breaking change for the API**
Expands the program serialization to contain the `username`.
=> Program serialization change

.travis.yml, dev.yml
- Persist data for redis
- Remove custom built postgres image
**Warning**: This will clear the local development database since this reverts back to the default database name of `postgres`
- Add redis-commander for debugging redis
We can remove `compose/nginx` and `compose/postgres` once `docker-compose.yml` no longer depends on them
=> Cleanup dev.yml

README.rst
I changed this two items in the README.RST because they were outdated and didn't work.
=> Fixing outdated setup instructions

.gitignore, .travis.yml, ecr-deploy.sh
This PR makes travis build and deploy the Docker image to our private Elastic Container Repository.
It relies on finding AWS role credentials in Travis' secret environment (newer feature of Travis, which is pretty cool). I've added them there.
We tag the image as either `alpha`, `beta`, or `prod`.
[Here is an example of a successful deploy on my working branch](https://travis-ci.org/rovercode/rovercode-web/builds/555073108).
=> Add ECR deploy

.travis.yml, compose/django/entrypoint.sh, config/settings/common.py, config/settings/production.py, env.example
We had already set up config/settings/common.py to read the Redis URL from the environment, but it was being overwritten in entrypoint.sh. This gets rid of the overwriting export in entrypoint.sh.
I created an ElastiCache Redis instance and ssh'd into our beta EC2 to test this change.
We can leave redis in the docker-compose for now so that the alpha environment can use on-instance redis to save money.
---------------
Unrelated: I also commented the ECR deploy until we're ready to resume work on the ECS cluster.
=> Off instance redis

realtime/consumers.py, realtime/tests/test_rover_consumer.py
This makes the websocket security check allow shared users. I realized I forgotten about this in the last shared-users PR.
=> Allow shared users to connect to ws

api/views.py
Only real use is to have all the tags so paginating just causes more API calls
=> Remove pagination from tag list

rovercode_web/templates/registration/password_reset_email.html
This sends the password reset to the correct UI route to enter the new password
=> Use correct route for password reset

config/settings/common.py, env.example, mission_control/signals/handlers.py
When the profanity-check service is not running on the same instance as the API, we need to be able to tell the API where to find it. This creates an environment variable for it.
I was playing with ECS some today. I think we'll set this new variable to the URL of the ALB, and the ALB will have a rule that routes the `/censor-word` path to the profanity service's target group.
=> Make profanity-check host an env variable

docker-compose.yml
This causes the deploy to fail since the dependency does not exist
=> Remove legacy dependency

compose/django/Dockerfile, compose/nginx/nginx-secure.conf
The image fails to build because the script no longer exists
=> Remove remaining websockets integration

.travis.yml
We don't need the CodeDeploy deploys for beta and prod in Travis anymore since we have the ECR deploy.
Removing these will allow us to deploy to prod ECR without overwriting our legacy prod EC2.
=> Get rid of CodeDeploy deploys for beta and prod

compose/django/Dockerfile
The updated version of `pipenv` does not allow running in root which is what Docker builds do. It's a known issue that will be fixed with a new release shortly. This should fix the build for now.
https://travis-ci.org/github/rovercode/rovercode-web/builds/693209738
=> Lock version of pipenv to build in Docker

api/tests/test_views.py, api/views.py, mission_control/pagination.py
Creates a new endpoint to view user statistics:
`/api/v1/users/<pk>/stats/`
Currently, contains the number of programs a user has and the maximum allowed in the free tier:
```
{
"block_diagram": {
"limit": 5,
"count": 120
}
}
```
=> User stats

api/views.py
This only worked by chance. Once the number was bigger than 256, this comparison failed. It was never the proper way to do it and this fixes the problem
=> Use proper user ID comparison

config/settings/production.py
We'll see if this goes easier on our little EC2 running sentry.
=> Reduce sentry traces sample rate

authorize/tests/test_views.py, authorize/views.py
Stores the `next` parameter in the session. Provides the value to the frontend in the callback response after the login has succeeded.
=> Provide 'next_url' to social login

api/urls.py, config/settings/common.py, rovercode_web/users/signals/handlers.py, rovercode_web/users/tests/test_utils.py, rovercode_web/users/utils.py
Fixes the JWT token refresh and verify views. The wrong serializers had been used when the library was changed. Now the correct parameters are used to refresh or verify the token.
=> Fix refresh and verify token views
